---

- include: map.yml

- name: install
  package:
    name: '{{ zabbix.agent.package }}'
    state: present

- name: configure
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix-agent
    group: zabbix-agent
    mode: '0644'

- name: enable and start
  service:
    name: "{{ zabbix.agent.service }}"
    state: started
    enabled: true
